/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.LayerRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param role 
 * @param garmentAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param providerId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param candidateCount 
 * @param maskAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 */
@Serializable

data class AddOutfitLayerRequest (

    @Contextual @SerialName(value = "role")
    val role: LayerRole,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "garment_asset_id")
    val garmentAssetId: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "provider_id")
    val providerId: java.util.UUID? = null,

    @SerialName(value = "candidate_count")
    val candidateCount: kotlin.Int? = null,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "mask_asset_id")
    val maskAssetId: java.util.UUID? = null

) {


}

