/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param authenticated 
 * @param csrfToken Returned in the login response and required for subsequent admin writes.
 * @param createdAt UTC RFC 3339 timestamp.
 * @param expiresAt UTC RFC 3339 timestamp.
 */
@Serializable

data class AdminSession (

    @SerialName(value = "authenticated")
    val authenticated: kotlin.Boolean,

    /* Returned in the login response and required for subsequent admin writes. */
    @SerialName(value = "csrf_token")
    val csrfToken: kotlin.String,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime

) {


}

