/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param authenticated 
 * @param tokenId Non-secret token identifier; never the token value.
 * @param serverTime UTC RFC 3339 timestamp.
 * @param serverInstanceId Stable opaque identity for this Backend installation. Local clients use it only as a partition key and must not derive trust from its value.
 * @param ownerScopeId Stable opaque material-owner scope associated with the App credential. It is independent of token rotation and reserves future account isolation.
 */
@Serializable

data class AppAuthStatus (

    @SerialName(value = "authenticated")
    val authenticated: kotlin.Boolean,

    /* Non-secret token identifier; never the token value. */
    @SerialName(value = "token_id")
    val tokenId: kotlin.String,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "server_time")
    val serverTime: java.time.OffsetDateTime,

    /* Stable opaque identity for this Backend installation. Local clients use it only as a partition key and must not derive trust from its value. */
    @Contextual @SerialName(value = "server_instance_id")
    val serverInstanceId: java.util.UUID? = null,

    /* Stable opaque material-owner scope associated with the App credential. It is independent of token rotation and reserves future account isolation. */
    @Contextual @SerialName(value = "owner_scope_id")
    val ownerScopeId: java.util.UUID? = null

) {


}

