/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param token One-time plaintext App Token. It is shown once and never returned again; the previous token is invalid immediately.
 * @param tokenId 
 * @param rotatedAt UTC RFC 3339 timestamp.
 */
@Serializable

data class AppCredentialRotation (

    /* One-time plaintext App Token. It is shown once and never returned again; the previous token is invalid immediately. */
    @SerialName(value = "token")
    val token: kotlin.String,

    @SerialName(value = "token_id")
    val tokenId: kotlin.String,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "rotated_at")
    val rotatedAt: java.time.OffsetDateTime

) {


}

