/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param tokenId Non-secret token identifier; never the token value.
 * @param status 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param rotatedAt UTC RFC 3339 timestamp.
 */
@Serializable

data class AppCredentialStatus (

    /* Non-secret token identifier; never the token value. */
    @SerialName(value = "token_id")
    val tokenId: kotlin.String,

    @SerialName(value = "status")
    val status: AppCredentialStatus.Status,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "rotated_at")
    val rotatedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: active,unknown,unknown_default_open_api
     */
    @Serializable(with = StatusSerializer::class)
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "unknown") unknown("unknown"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object StatusSerializer : KSerializer<Status> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Status {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Status.entries.firstOrNull { it.value == value }
                ?: Status.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Status) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

