/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.AssetKind
import com.clothesmodel.contract.model.GarmentCategory
import com.clothesmodel.contract.model.GarmentSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param kind 
 * @param contentType 
 * @param sizeBytes 
 * @param width 
 * @param height 
 * @param favorite 
 * @param lifecycle 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param contentAvailable 
 * @param qualityWarnings 
 * @param garmentCategory 
 * @param garmentSource 
 */
@Serializable

data class Asset (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "kind")
    val kind: AssetKind,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "width")
    val width: kotlin.Int,

    @SerialName(value = "height")
    val height: kotlin.Int,

    @SerialName(value = "favorite")
    val favorite: kotlin.Boolean,

    @SerialName(value = "lifecycle")
    val lifecycle: Asset.Lifecycle,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "content_available")
    val contentAvailable: kotlin.Boolean,

    @SerialName(value = "quality_warnings")
    val qualityWarnings: kotlin.collections.List<kotlin.String>? = null,

    @Contextual @SerialName(value = "garment_category")
    val garmentCategory: GarmentCategory? = null,

    @Contextual @SerialName(value = "garment_source")
    val garmentSource: GarmentSource? = null

) {

    /**
     * 
     *
     * Values: active,deleted_content,expired,unknown,unknown_default_open_api
     */
    @Serializable(with = LifecycleSerializer::class)
    enum class Lifecycle(val value: kotlin.String) {
        @SerialName(value = "active") active("active"),
        @SerialName(value = "deleted_content") deleted_content("deleted_content"),
        @SerialName(value = "expired") expired("expired"),
        @SerialName(value = "unknown") unknown("unknown"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object LifecycleSerializer : KSerializer<Lifecycle> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Lifecycle {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Lifecycle.entries.firstOrNull { it.value == value }
                ?: Lifecycle.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Lifecycle) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

