/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param clientAssetId Opaque Android-local material identifier used for idempotent acknowledgement.
 * @param sha256 Digest verified from the durable Android private copy.
 */
@Serializable

data class AssetLocalCopyAcknowledgement (

    /* Opaque Android-local material identifier used for idempotent acknowledgement. */
    @Contextual @SerialName(value = "client_asset_id")
    val clientAssetId: java.util.UUID,

    /* Digest verified from the durable Android private copy. */
    @SerialName(value = "sha256")
    val sha256: kotlin.String

) {


}

