/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * Stable source family. Unknown values remain safe for older clients.
 *
 * Values: job,job_item,outfit,generated_output,unknown,unknown_default_open_api
 */
@Serializable(with = AssetReferenceKindSerializer::class)
enum class AssetReferenceKind(val value: kotlin.String) {

    @SerialName(value = "job")
    job("job"),

    @SerialName(value = "job_item")
    job_item("job_item"),

    @SerialName(value = "outfit")
    outfit("outfit"),

    @SerialName(value = "generated_output")
    generated_output("generated_output"),

    @SerialName(value = "unknown")
    unknown("unknown"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AssetReferenceKind) "$data" else null

        /**
         * Returns a valid [AssetReferenceKind] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AssetReferenceKind? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object AssetReferenceKindSerializer : KSerializer<AssetReferenceKind> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): AssetReferenceKind {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return AssetReferenceKind.entries.firstOrNull { it.value == value }
            ?: AssetReferenceKind.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: AssetReferenceKind) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


