/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.AssetReferenceKind

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param assetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param sourceKind 
 * @param sourceId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param active 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param label Safe display label captured by the referencing module.
 */
@Serializable

data class AssetReference (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "asset_id")
    val assetId: java.util.UUID,

    @Contextual @SerialName(value = "source_kind")
    val sourceKind: AssetReferenceKind,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "source_id")
    val sourceId: java.util.UUID,

    @SerialName(value = "active")
    val active: kotlin.Boolean,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Safe display label captured by the referencing module. */
    @SerialName(value = "label")
    val label: kotlin.String? = null

) {


}

