/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.CapabilitySource
import com.clothesmodel.contract.model.CapabilityVerification

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param supported 
 * @param source 
 * @param verification 
 * @param note 
 */
@Serializable

data class CapabilityFlag (

    @SerialName(value = "supported")
    val supported: kotlin.Boolean,

    @Contextual @SerialName(value = "source")
    val source: CapabilitySource,

    @Contextual @SerialName(value = "verification")
    val verification: CapabilityVerification,

    @SerialName(value = "note")
    val note: kotlin.String? = null

) {


}

