/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param deletedFiles 
 * @param reclaimedBytes 
 * @param skippedProtectedFiles 
 * @param completedAt UTC RFC 3339 timestamp.
 */
@Serializable

data class CleanupResult (

    @SerialName(value = "deleted_files")
    val deletedFiles: kotlin.Int,

    @SerialName(value = "reclaimed_bytes")
    val reclaimedBytes: kotlin.Long,

    @SerialName(value = "skipped_protected_files")
    val skippedProtectedFiles: kotlin.Int,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime

) {


}

