/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param endpoint 
 * @param timeoutSeconds 
 * @param enabled 
 * @param credentialConfigured 
 * @param health 
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param credentialUpdatedAt 
 * @param lastCheckedAt 
 */
@Serializable

data class ComfyNodeConfiguration (

    @Contextual @SerialName(value = "endpoint")
    val endpoint: java.net.URI,

    @SerialName(value = "timeout_seconds")
    val timeoutSeconds: kotlin.Int,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    @SerialName(value = "credential_configured")
    val credentialConfigured: kotlin.Boolean,

    @SerialName(value = "health")
    val health: ComfyNodeConfiguration.Health,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "credential_updated_at")
    val credentialUpdatedAt: java.time.OffsetDateTime? = null,

    @Contextual @SerialName(value = "last_checked_at")
    val lastCheckedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: healthy,offline,unchecked,incompatible,unknown,unknown_default_open_api
     */
    @Serializable(with = HealthSerializer::class)
    enum class Health(val value: kotlin.String) {
        @SerialName(value = "healthy") healthy("healthy"),
        @SerialName(value = "offline") offline("offline"),
        @SerialName(value = "unchecked") unchecked("unchecked"),
        @SerialName(value = "incompatible") incompatible("incompatible"),
        @SerialName(value = "unknown") unknown("unknown"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object HealthSerializer : KSerializer<Health> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Health {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Health.entries.firstOrNull { it.value == value }
                ?: Health.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Health) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

