/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param endpoint 
 * @param timeoutSeconds 
 * @param enabled 
 * @param credential Omit to retain the configured credential; supply only to create or overwrite it.
 */
@Serializable

data class ComfyNodeConfigurationRequest (

    @Contextual @SerialName(value = "endpoint")
    val endpoint: java.net.URI,

    @SerialName(value = "timeout_seconds")
    val timeoutSeconds: kotlin.Int,

    @SerialName(value = "enabled")
    val enabled: kotlin.Boolean,

    /* Omit to retain the configured credential; supply only to create or overwrite it. */
    @SerialName(value = "credential")
    val credential: kotlin.String? = null

) {


}

