/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.GenerationOptions
import com.clothesmodel.contract.model.OutfitJobContext
import com.clothesmodel.contract.model.TryOnMode

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param personAssetIds V1 submits one person asset while preserving the future-safe list shape.
 * @param garmentAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param providerId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param mode 
 * @param generationOptions 
 * @param maskAssetId 
 * @param relatedJobId Links a mask-correction job to the original job without overwriting it.
 * @param outfitContext Present only for V1.1 layered-outfit layer jobs. V1 jobs omit it and keep their behavior.
 */
@Serializable

data class CreateJobRequest (

    /* V1 submits one person asset while preserving the future-safe list shape. */
    @SerialName(value = "person_asset_ids")
    val personAssetIds: kotlin.collections.List<@Contextual java.util.UUID>,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "garment_asset_id")
    val garmentAssetId: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "provider_id")
    val providerId: java.util.UUID,

    @Contextual @SerialName(value = "mode")
    val mode: TryOnMode,

    @SerialName(value = "generation_options")
    val generationOptions: GenerationOptions,

    @Contextual @SerialName(value = "mask_asset_id")
    val maskAssetId: java.util.UUID? = null,

    /* Links a mask-correction job to the original job without overwriting it. */
    @Contextual @SerialName(value = "related_job_id")
    val relatedJobId: java.util.UUID? = null,

    /* Present only for V1.1 layered-outfit layer jobs. V1 jobs omit it and keep their behavior. */
    @SerialName(value = "outfit_context")
    val outfitContext: OutfitJobContext? = null

) {


}

