/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderConfigRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param providerId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param configRef 
 * @param updatedAt UTC RFC 3339 timestamp.
 */
@Serializable

data class DefaultProviderConfiguration (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "provider_id")
    val providerId: java.util.UUID,

    @SerialName(value = "config_ref")
    val configRef: ProviderConfigRef,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime

) {


}

