/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param at UTC RFC 3339 timestamp.
 * @param category 
 * @param conclusion 
 */
@Serializable

data class DiagnosticJobDetailRedactedExternalEventsInner (

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "at")
    val at: java.time.OffsetDateTime,

    @SerialName(value = "category")
    val category: kotlin.String,

    @SerialName(value = "conclusion")
    val conclusion: kotlin.String

) {


}

