/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderConfigRef
import com.clothesmodel.contract.model.WorkflowVersionRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param defaultProvider 
 * @param activeLlmProvider 
 * @param activeWorkflow 
 */
@Serializable

data class EffectiveConfiguration (

    @SerialName(value = "default_provider")
    val defaultProvider: ProviderConfigRef? = null,

    @SerialName(value = "active_llm_provider")
    val activeLlmProvider: ProviderConfigRef? = null,

    @SerialName(value = "active_workflow")
    val activeWorkflow: WorkflowVersionRef? = null

) {


}

