/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param candidateCount 
 * @param seed 
 * @param advancedParameters 
 */
@Serializable

data class GenerationOptions (

    @SerialName(value = "candidate_count")
    val candidateCount: kotlin.Int,

    @SerialName(value = "seed")
    val seed: kotlin.Long? = null,

    @Contextual @SerialName(value = "advanced_parameters")
    val advancedParameters: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null

) {


}

