/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param jobItemId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param assetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param favorite 
 * @param contentAvailable 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param seed 
 * @param actualParameters 
 * @param qualityWarnings 
 */
@Serializable

data class GeneratedOutput (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "job_item_id")
    val jobItemId: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "asset_id")
    val assetId: java.util.UUID,

    @SerialName(value = "favorite")
    val favorite: kotlin.Boolean,

    @SerialName(value = "content_available")
    val contentAvailable: kotlin.Boolean,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "seed")
    val seed: kotlin.Long? = null,

    @Contextual @SerialName(value = "actual_parameters")
    val actualParameters: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

    @SerialName(value = "quality_warnings")
    val qualityWarnings: kotlin.collections.List<kotlin.String>? = null

) {


}

