/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param status 
 * @param checkedAt UTC RFC 3339 timestamp.
 * @param checks Safe component conclusions without filesystem paths or secrets.
 */
@Serializable

data class HealthStatus (

    @SerialName(value = "status")
    val status: HealthStatus.Status,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "checked_at")
    val checkedAt: java.time.OffsetDateTime,

    /* Safe component conclusions without filesystem paths or secrets. */
    @SerialName(value = "checks")
    val checks: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {

    /**
     * 
     *
     * Values: ok,unavailable,unknown_default_open_api
     */
    @Serializable(with = StatusSerializer::class)
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "ok") ok("ok"),
        @SerialName(value = "unavailable") unavailable("unavailable"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object StatusSerializer : KSerializer<Status> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Status {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Status.entries.firstOrNull { it.value == value }
                ?: Status.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Status) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

