/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param contentTypes 
 * @param maxSizeBytes 
 * @param minWidth 
 * @param minHeight 
 * @param maxWidth 
 * @param maxHeight 
 */
@Serializable

data class ImageConstraints (

    @SerialName(value = "content_types")
    val contentTypes: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "max_size_bytes")
    val maxSizeBytes: kotlin.Long,

    @SerialName(value = "min_width")
    val minWidth: kotlin.Int? = null,

    @SerialName(value = "min_height")
    val minHeight: kotlin.Int? = null,

    @SerialName(value = "max_width")
    val maxWidth: kotlin.Int? = null,

    @SerialName(value = "max_height")
    val maxHeight: kotlin.Int? = null

) {


}

