/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * 
 *
 * Values: provider_offline,storage_capacity,retry_backoff,locked_configuration_unavailable,external_state_unknown,configuration_invalid,unknown,unknown_default_open_api
 */
@Serializable(with = JobBlockReasonSerializer::class)
enum class JobBlockReason(val value: kotlin.String) {

    @SerialName(value = "provider_offline")
    provider_offline("provider_offline"),

    @SerialName(value = "storage_capacity")
    storage_capacity("storage_capacity"),

    @SerialName(value = "retry_backoff")
    retry_backoff("retry_backoff"),

    @SerialName(value = "locked_configuration_unavailable")
    locked_configuration_unavailable("locked_configuration_unavailable"),

    @SerialName(value = "external_state_unknown")
    external_state_unknown("external_state_unknown"),

    @SerialName(value = "configuration_invalid")
    configuration_invalid("configuration_invalid"),

    @SerialName(value = "unknown")
    unknown("unknown"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JobBlockReason) "$data" else null

        /**
         * Returns a valid [JobBlockReason] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JobBlockReason? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object JobBlockReasonSerializer : KSerializer<JobBlockReason> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): JobBlockReason {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return JobBlockReason.entries.firstOrNull { it.value == value }
            ?: JobBlockReason.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: JobBlockReason) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


