/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.GeneratedOutput
import com.clothesmodel.contract.model.JobBlockReason
import com.clothesmodel.contract.model.JobItemState
import com.clothesmodel.contract.model.ProblemDetails

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param jobId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param personAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param candidateIndex 
 * @param state 
 * @param attempt 
 * @param outputs 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param blockReason 
 * @param retryOfJobItemId 
 * @param supersededByJobItemId Newer attempt for the same candidate that replaced this retained attempt; null or absent while this is the latest attempt in the candidate lineage.
 * @param externalExecutionId Safe provider execution identifier; provider credentials are never included.
 * @param nextAttemptAt 
 * @param error 
 */
@Serializable

data class JobItem (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "job_id")
    val jobId: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "person_asset_id")
    val personAssetId: java.util.UUID,

    @SerialName(value = "candidate_index")
    val candidateIndex: kotlin.Int,

    @Contextual @SerialName(value = "state")
    val state: JobItemState,

    @SerialName(value = "attempt")
    val attempt: kotlin.Int,

    @SerialName(value = "outputs")
    val outputs: kotlin.collections.List<GeneratedOutput>,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "block_reason")
    val blockReason: JobBlockReason? = null,

    @Contextual @SerialName(value = "retry_of_job_item_id")
    val retryOfJobItemId: java.util.UUID? = null,

    /* Newer attempt for the same candidate that replaced this retained attempt; null or absent while this is the latest attempt in the candidate lineage. */
    @Contextual @SerialName(value = "superseded_by_job_item_id")
    val supersededByJobItemId: java.util.UUID? = null,

    /* Safe provider execution identifier; provider credentials are never included. */
    @SerialName(value = "external_execution_id")
    val externalExecutionId: kotlin.String? = null,

    @Contextual @SerialName(value = "next_attempt_at")
    val nextAttemptAt: java.time.OffsetDateTime? = null,

    @SerialName(value = "error")
    val error: ProblemDetails? = null

) {


}

