/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * 
 *
 * Values: queued,waiting_provider,preparing,running,needs_attention,succeeded,partially_succeeded,failed,cancelled,unknown,unknown_default_open_api
 */
@Serializable(with = JobStateSerializer::class)
enum class JobState(val value: kotlin.String) {

    @SerialName(value = "queued")
    queued("queued"),

    @SerialName(value = "waiting_provider")
    waiting_provider("waiting_provider"),

    @SerialName(value = "preparing")
    preparing("preparing"),

    @SerialName(value = "running")
    running("running"),

    @SerialName(value = "needs_attention")
    needs_attention("needs_attention"),

    @SerialName(value = "succeeded")
    succeeded("succeeded"),

    @SerialName(value = "partially_succeeded")
    partially_succeeded("partially_succeeded"),

    @SerialName(value = "failed")
    failed("failed"),

    @SerialName(value = "cancelled")
    cancelled("cancelled"),

    @SerialName(value = "unknown")
    unknown("unknown"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is JobState) "$data" else null

        /**
         * Returns a valid [JobState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): JobState? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object JobStateSerializer : KSerializer<JobState> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): JobState {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return JobState.entries.firstOrNull { it.value == value }
            ?: JobState.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: JobState) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


