/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.LayerRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param key 
 * @param bodyRegion 
 * @param order 
 * @param compatibleRoles 
 * @param conflictingRoles 
 * @param requiredCapabilities 
 */
@Serializable

data class LayerTypeDefinition (

    @Contextual @SerialName(value = "key")
    val key: LayerRole,

    @SerialName(value = "body_region")
    val bodyRegion: kotlin.String,

    @SerialName(value = "order")
    val order: kotlin.Int,

    @SerialName(value = "compatible_roles")
    val compatibleRoles: kotlin.collections.List<@Contextual LayerRole>,

    @SerialName(value = "conflicting_roles")
    val conflictingRoles: kotlin.collections.List<@Contextual LayerRole>,

    @SerialName(value = "required_capabilities")
    val requiredCapabilities: kotlin.collections.List<kotlin.String>? = null

) {


}

