/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.LayerRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param sessionId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param branchId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param layerId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param role 
 * @param baseRevisionId Server-issued UUIDv7 represented as a canonical UUID string.
 */
@Serializable

data class OutfitJobContext (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "session_id")
    val sessionId: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "layer_id")
    val layerId: java.util.UUID,

    @Contextual @SerialName(value = "role")
    val role: LayerRole,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "base_revision_id")
    val baseRevisionId: java.util.UUID? = null

) {


}

