/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.OutfitLayer
import com.clothesmodel.contract.model.OutfitRoute

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param name 
 * @param route 
 * @param isMainline 
 * @param favorite 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param headRevisionId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param revisionCount 
 * @param unfinishedJobCount 
 * @param layers Current working-layer set for this branch, including layers awaiting reapply. It may differ from the last confirmed revision.
 */
@Serializable

data class OutfitBranch (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @Contextual @SerialName(value = "route")
    val route: OutfitRoute,

    @SerialName(value = "is_mainline")
    val isMainline: kotlin.Boolean,

    @SerialName(value = "favorite")
    val favorite: kotlin.Boolean,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "head_revision_id")
    val headRevisionId: java.util.UUID? = null,

    @SerialName(value = "revision_count")
    val revisionCount: kotlin.Int? = null,

    @SerialName(value = "unfinished_job_count")
    val unfinishedJobCount: kotlin.Int? = null,

    /* Current working-layer set for this branch, including layers awaiting reapply. It may differ from the last confirmed revision. */
    @SerialName(value = "layers")
    val layers: kotlin.collections.List<OutfitLayer>? = null

) {


}

