/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.LayerApplyState
import com.clothesmodel.contract.model.LayerRole

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param role 
 * @param garmentAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param order 
 * @param state 
 * @param definitionVersion 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param sourceLayerId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param applyJobId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param selectedOutputId Server-issued UUIDv7 represented as a canonical UUID string.
 */
@Serializable

data class OutfitLayer (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "role")
    val role: LayerRole,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "garment_asset_id")
    val garmentAssetId: java.util.UUID,

    @SerialName(value = "order")
    val order: kotlin.Int,

    @Contextual @SerialName(value = "state")
    val state: LayerApplyState,

    @SerialName(value = "definition_version")
    val definitionVersion: kotlin.Int,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "source_layer_id")
    val sourceLayerId: java.util.UUID? = null,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "apply_job_id")
    val applyJobId: java.util.UUID? = null,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "selected_output_id")
    val selectedOutputId: java.util.UUID? = null

) {


}

