/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.OutfitLayer

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param branchId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param layers 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param baseRevisionId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param parentRevisionId Server-issued UUIDv7 represented as a canonical UUID string.
 */
@Serializable

data class OutfitRevision (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "branch_id")
    val branchId: java.util.UUID,

    @SerialName(value = "layers")
    val layers: kotlin.collections.List<OutfitLayer>,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "base_revision_id")
    val baseRevisionId: java.util.UUID? = null,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "parent_revision_id")
    val parentRevisionId: java.util.UUID? = null

) {


}

