/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.LayerTypeDefinition
import com.clothesmodel.contract.model.OutfitBranch
import com.clothesmodel.contract.model.OutfitRevision

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param name 
 * @param favorite 
 * @param personAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param layerDefinitionVersion 
 * @param layerTypes 
 * @param branches 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param mainBranchId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param headRevision 
 */
@Serializable

data class OutfitSession (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "name")
    val name: kotlin.String,

    @SerialName(value = "favorite")
    val favorite: kotlin.Boolean,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "person_asset_id")
    val personAssetId: java.util.UUID,

    @SerialName(value = "layer_definition_version")
    val layerDefinitionVersion: kotlin.Int,

    @SerialName(value = "layer_types")
    val layerTypes: kotlin.collections.List<LayerTypeDefinition>,

    @SerialName(value = "branches")
    val branches: kotlin.collections.List<OutfitBranch>,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "main_branch_id")
    val mainBranchId: java.util.UUID? = null,

    @SerialName(value = "head_revision")
    val headRevision: OutfitRevision? = null

) {


}

