/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.FieldError

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param type 
 * @param title 
 * @param status 
 * @param code Stable machine-readable error code. Clients must not branch on detail text.
 * @param detail Safe Chinese user-facing explanation.
 * @param traceId 
 * @param retryable 
 * @param fieldErrors 
 * @param context Safe structured context only; never contains secrets or raw provider payloads.
 */
@Serializable

data class ProblemDetails (

    @Contextual @SerialName(value = "type")
    val type: java.net.URI,

    @SerialName(value = "title")
    val title: kotlin.String,

    @SerialName(value = "status")
    val status: kotlin.Int,

    /* Stable machine-readable error code. Clients must not branch on detail text. */
    @SerialName(value = "code")
    val code: kotlin.String,

    /* Safe Chinese user-facing explanation. */
    @SerialName(value = "detail")
    val detail: kotlin.String,

    @SerialName(value = "trace_id")
    val traceId: kotlin.String,

    @SerialName(value = "retryable")
    val retryable: kotlin.Boolean,

    @SerialName(value = "field_errors")
    val fieldErrors: kotlin.collections.List<FieldError>,

    /* Safe structured context only; never contains secrets or raw provider payloads. */
    @Contextual @SerialName(value = "context")
    val context: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>

) {


}

