/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder


/**
 * Server-authoritative product release track for exposed behavior.
 *
 * Values: v1,v1_1,unknown_default_open_api
 */
@Serializable(with = ProductReleaseSerializer::class)
enum class ProductRelease(val value: kotlin.String) {

    @SerialName(value = "v1")
    v1("v1"),

    @SerialName(value = "v1_1")
    v1_1("v1_1"),

    @SerialName(value = "unknown_default_open_api")
    unknown_default_open_api("unknown_default_open_api");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ProductRelease) "$data" else null

        /**
         * Returns a valid [ProductRelease] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ProductRelease? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

internal object ProductReleaseSerializer : KSerializer<ProductRelease> {
    override val descriptor = kotlin.String.serializer().descriptor

    override fun deserialize(decoder: Decoder): ProductRelease {
        val value = decoder.decodeSerializableValue(kotlin.String.serializer())
        return ProductRelease.entries.firstOrNull { it.value == value }
            ?: ProductRelease.unknown_default_open_api
    }

    override fun serialize(encoder: Encoder, value: ProductRelease) {
        encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
    }
}


