/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.CapabilityFlag
import com.clothesmodel.contract.model.CapabilityValues
import com.clothesmodel.contract.model.ImageConstraints
import com.clothesmodel.contract.model.OutputConstraints

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param schemaVersion 
 * @param garmentCategories 
 * @param manualMask 
 * @param multipleCandidates 
 * @param multiPersonReference 
 * @param batchInput 
 * @param interruptRunning 
 * @param sequentialLayering 
 * @param supportedLayerRoles 
 * @param preserveExistingGarments 
 * @param outfitContext 
 * @param regionMask 
 * @param inputConstraints 
 * @param outputConstraints 
 */
@Serializable

data class ProviderCapabilities (

    @SerialName(value = "schema_version")
    val schemaVersion: ProviderCapabilities.SchemaVersion,

    @SerialName(value = "garment_categories")
    val garmentCategories: CapabilityValues,

    @SerialName(value = "manual_mask")
    val manualMask: CapabilityFlag,

    @SerialName(value = "multiple_candidates")
    val multipleCandidates: CapabilityFlag,

    @SerialName(value = "multi_person_reference")
    val multiPersonReference: CapabilityFlag,

    @SerialName(value = "batch_input")
    val batchInput: CapabilityFlag,

    @SerialName(value = "interrupt_running")
    val interruptRunning: CapabilityFlag,

    @SerialName(value = "sequential_layering")
    val sequentialLayering: CapabilityFlag,

    @SerialName(value = "supported_layer_roles")
    val supportedLayerRoles: CapabilityValues,

    @SerialName(value = "preserve_existing_garments")
    val preserveExistingGarments: CapabilityFlag,

    @SerialName(value = "outfit_context")
    val outfitContext: CapabilityFlag,

    @SerialName(value = "region_mask")
    val regionMask: CapabilityFlag,

    @SerialName(value = "input_constraints")
    val inputConstraints: ImageConstraints,

    @SerialName(value = "output_constraints")
    val outputConstraints: OutputConstraints

) {

    /**
     * 
     *
     * Values: _1,unknown_default_open_api
     */
    @Serializable(with = SchemaVersionSerializer::class)
    enum class SchemaVersion(val value: kotlin.Int) {
        @SerialName(value = "1") _1(1),
        @SerialName(value = "11184809") unknown_default_open_api(11184809);
    }

    internal object SchemaVersionSerializer : KSerializer<SchemaVersion> {
        override val descriptor = kotlin.Int.serializer().descriptor

        override fun deserialize(decoder: Decoder): SchemaVersion {
            val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
            return SchemaVersion.entries.firstOrNull { it.value == value }
                ?: SchemaVersion.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: SchemaVersion) {
            encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
        }
    }

}

