/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderCapabilities
import com.clothesmodel.contract.model.ProviderConfigRef
import com.clothesmodel.contract.model.ProviderConfigState
import com.clothesmodel.contract.model.ProviderType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param displayName 
 * @param type 
 * @param adapterType 
 * @param endpoint Logical adapter endpoint for ordinary Providers. The ComfyUI physical node endpoint is owned by ComfyNodeConfiguration and is not locked into historical jobs.
 * @param model 
 * @param timeoutSeconds 
 * @param state 
 * @param secretConfigured 
 * @param configRef 
 * @param capabilities 
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param secretUpdatedAt 
 */
@Serializable

data class ProviderConfig (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: ProviderType,

    @SerialName(value = "adapter_type")
    val adapterType: kotlin.String,

    /* Logical adapter endpoint for ordinary Providers. The ComfyUI physical node endpoint is owned by ComfyNodeConfiguration and is not locked into historical jobs. */
    @Contextual @SerialName(value = "endpoint")
    val endpoint: java.net.URI,

    @SerialName(value = "model")
    val model: kotlin.String,

    @SerialName(value = "timeout_seconds")
    val timeoutSeconds: kotlin.Int,

    @Contextual @SerialName(value = "state")
    val state: ProviderConfigState,

    @SerialName(value = "secret_configured")
    val secretConfigured: kotlin.Boolean,

    @SerialName(value = "config_ref")
    val configRef: ProviderConfigRef,

    @SerialName(value = "capabilities")
    val capabilities: ProviderCapabilities,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "secret_updated_at")
    val secretUpdatedAt: java.time.OffsetDateTime? = null

) {


}

