/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderAvailability
import com.clothesmodel.contract.model.ProviderCapabilities
import com.clothesmodel.contract.model.ProviderConfigRef
import com.clothesmodel.contract.model.ProviderType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Selectable logical Provider summary. For ComfyUI, id does not identify or lock the replaceable physical node endpoint.
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param displayName 
 * @param type 
 * @param availability 
 * @param configRef 
 * @param capabilities 
 * @param unavailableReason 
 * @param isDefault 
 */
@Serializable

data class ProviderSummary (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: ProviderType,

    @Contextual @SerialName(value = "availability")
    val availability: ProviderAvailability,

    @SerialName(value = "config_ref")
    val configRef: ProviderConfigRef,

    @SerialName(value = "capabilities")
    val capabilities: ProviderCapabilities,

    @SerialName(value = "unavailable_reason")
    val unavailableReason: kotlin.String? = null,

    @SerialName(value = "is_default")
    val isDefault: kotlin.Boolean? = null

) {


}

