/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderCapabilities
import com.clothesmodel.contract.model.ProviderValidationResultStepsInner

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param status 
 * @param checkedAt UTC RFC 3339 timestamp.
 * @param steps 
 * @param capabilities 
 */
@Serializable

data class ProviderValidationResult (

    @SerialName(value = "status")
    val status: ProviderValidationResult.Status,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "checked_at")
    val checkedAt: java.time.OffsetDateTime,

    @SerialName(value = "steps")
    val steps: kotlin.collections.List<ProviderValidationResultStepsInner>,

    @SerialName(value = "capabilities")
    val capabilities: ProviderCapabilities

) {

    /**
     * 
     *
     * Values: passed,failed,unknown_default_open_api
     */
    @Serializable(with = StatusSerializer::class)
    enum class Status(val value: kotlin.String) {
        @SerialName(value = "passed") passed("passed"),
        @SerialName(value = "failed") failed("failed"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object StatusSerializer : KSerializer<Status> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Status {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Status.entries.firstOrNull { it.value == value }
                ?: Status.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Status) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

