/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderCapabilities

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * Immutable copy of the generation-semantic Provider configuration captured when the job was created. Later default or configuration changes never alter it. Encrypted credentials are referenced through provider_config_ref and are never copied into this snapshot or any API response.
 *
 * @param label Read-only display label captured at creation.
 * @param adapterType Adapter implementation selected for this job's locked semantics.
 * @param model Locked model or workflow identity that shapes generation semantics.
 * @param semanticParameters Locked non-secret vendor/model parameters that affect generation.
 * @param capabilitiesSchemaVersion 
 * @param capabilities 
 */
@Serializable

data class ProviderSnapshot (

    /* Read-only display label captured at creation. */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* Adapter implementation selected for this job's locked semantics. */
    @SerialName(value = "adapter_type")
    val adapterType: kotlin.String? = null,

    /* Locked model or workflow identity that shapes generation semantics. */
    @SerialName(value = "model")
    val model: kotlin.String? = null,

    /* Locked non-secret vendor/model parameters that affect generation. */
    @Contextual @SerialName(value = "semantic_parameters")
    val semanticParameters: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null,

    @SerialName(value = "capabilities_schema_version")
    val capabilitiesSchemaVersion: ProviderSnapshot.CapabilitiesSchemaVersion? = null,

    @SerialName(value = "capabilities")
    val capabilities: ProviderCapabilities? = null

) {

    /**
     * 
     *
     * Values: _1,unknown_default_open_api
     */
    @Serializable(with = CapabilitiesSchemaVersionSerializer::class)
    enum class CapabilitiesSchemaVersion(val value: kotlin.Int) {
        @SerialName(value = "1") _1(1),
        @SerialName(value = "11184809") unknown_default_open_api(11184809);
    }

    internal object CapabilitiesSchemaVersionSerializer : KSerializer<CapabilitiesSchemaVersion> {
        override val descriptor = kotlin.Int.serializer().descriptor

        override fun deserialize(decoder: Decoder): CapabilitiesSchemaVersion {
            val value = decoder.decodeSerializableValue(kotlin.Int.serializer())
            return CapabilitiesSchemaVersion.entries.firstOrNull { it.value == value }
                ?: CapabilitiesSchemaVersion.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: CapabilitiesSchemaVersion) {
            encoder.encodeSerializableValue(kotlin.Int.serializer(), value.value)
        }
    }

}

