/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderType

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param displayName 
 * @param type 
 * @param adapterType 
 * @param endpoint 
 * @param model 
 * @param timeoutSeconds 
 * @param apiKey Omit to retain an existing secret; supply only to create or overwrite it.
 * @param vendorParameters 
 */
@Serializable

data class ProviderConfigRequest (

    @SerialName(value = "display_name")
    val displayName: kotlin.String,

    @Contextual @SerialName(value = "type")
    val type: ProviderType,

    @SerialName(value = "adapter_type")
    val adapterType: kotlin.String,

    @Contextual @SerialName(value = "endpoint")
    val endpoint: java.net.URI,

    @SerialName(value = "model")
    val model: kotlin.String,

    @SerialName(value = "timeout_seconds")
    val timeoutSeconds: kotlin.Int,

    /* Omit to retain an existing secret; supply only to create or overwrite it. */
    @SerialName(value = "api_key")
    val apiKey: kotlin.String? = null,

    @Contextual @SerialName(value = "vendor_parameters")
    val vendorParameters: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>? = null

) {


}

