/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param mode 
 */
@Serializable

data class RemoveOutfitLayerRequest (

    @SerialName(value = "mode")
    val mode: RemoveOutfitLayerRequest.Mode? = null

) {

    /**
     * 
     *
     * Values: remove,revert,unknown_default_open_api
     */
    @Serializable(with = ModeSerializer::class)
    enum class Mode(val value: kotlin.String) {
        @SerialName(value = "remove") remove("remove"),
        @SerialName(value = "revert") revert("revert"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object ModeSerializer : KSerializer<Mode> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Mode {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Mode.entries.firstOrNull { it.value == value }
                ?: Mode.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Mode) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

