/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param scanId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param reclaimableBytes 
 * @param reclaimableFiles 
 * @param protectedFiles 
 * @param completedAt UTC RFC 3339 timestamp.
 */
@Serializable

data class StorageScanResult (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "scan_id")
    val scanId: java.util.UUID,

    @SerialName(value = "reclaimable_bytes")
    val reclaimableBytes: kotlin.Long,

    @SerialName(value = "reclaimable_files")
    val reclaimableFiles: kotlin.Int,

    @SerialName(value = "protected_files")
    val protectedFiles: kotlin.Int,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "completed_at")
    val completedAt: java.time.OffsetDateTime

) {


}

