/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param state 
 * @param capacityBytes 
 * @param usedBytes 
 * @param availableBytes 
 * @param acceptingNewWork 
 * @param checkedAt UTC RFC 3339 timestamp.
 * @param blockReason 
 */
@Serializable

data class StorageStatus (

    @SerialName(value = "state")
    val state: StorageStatus.State,

    @SerialName(value = "capacity_bytes")
    val capacityBytes: kotlin.Long,

    @SerialName(value = "used_bytes")
    val usedBytes: kotlin.Long,

    @SerialName(value = "available_bytes")
    val availableBytes: kotlin.Long,

    @SerialName(value = "accepting_new_work")
    val acceptingNewWork: kotlin.Boolean,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "checked_at")
    val checkedAt: java.time.OffsetDateTime,

    @SerialName(value = "block_reason")
    val blockReason: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: healthy,warning,blocked,unknown,unknown_default_open_api
     */
    @Serializable(with = StateSerializer::class)
    enum class State(val value: kotlin.String) {
        @SerialName(value = "healthy") healthy("healthy"),
        @SerialName(value = "warning") warning("warning"),
        @SerialName(value = "blocked") blocked("blocked"),
        @SerialName(value = "unknown") unknown("unknown"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object StateSerializer : KSerializer<State> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): State {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return State.entries.firstOrNull { it.value == value }
                ?: State.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: State) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

