/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.SystemActionSeverity
import com.clothesmodel.contract.model.SystemActionTargetKind

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id 
 * @param severity 
 * @param summary 
 * @param targetKind 
 * @param targetId 
 */
@Serializable

data class SystemActionItem (

    @SerialName(value = "id")
    val id: kotlin.String,

    @Contextual @SerialName(value = "severity")
    val severity: SystemActionSeverity,

    @SerialName(value = "summary")
    val summary: kotlin.String,

    @Contextual @SerialName(value = "target_kind")
    val targetKind: SystemActionTargetKind,

    @SerialName(value = "target_id")
    val targetId: kotlin.String? = null

) {


}

