/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.EffectiveConfiguration
import com.clothesmodel.contract.model.SystemActionItem
import com.clothesmodel.contract.model.SystemBlocker
import com.clothesmodel.contract.model.SystemDependency
import com.clothesmodel.contract.model.SystemOverviewVerdict

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param verdict 
 * @param snapshotAt UTC RFC 3339 timestamp.
 * @param dependencies 
 * @param blockers 
 * @param actionItems 
 * @param effectiveConfiguration 
 */
@Serializable

data class SystemOverview (

    @Contextual @SerialName(value = "verdict")
    val verdict: SystemOverviewVerdict,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "snapshot_at")
    val snapshotAt: java.time.OffsetDateTime,

    @SerialName(value = "dependencies")
    val dependencies: kotlin.collections.List<SystemDependency>,

    @SerialName(value = "blockers")
    val blockers: kotlin.collections.List<SystemBlocker>,

    @SerialName(value = "action_items")
    val actionItems: kotlin.collections.List<SystemActionItem>,

    @SerialName(value = "effective_configuration")
    val effectiveConfiguration: EffectiveConfiguration

) {


}

