/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.GenerationOptions
import com.clothesmodel.contract.model.JobBlockReason
import com.clothesmodel.contract.model.JobItem
import com.clothesmodel.contract.model.JobState
import com.clothesmodel.contract.model.ProviderConfigRef
import com.clothesmodel.contract.model.TryOnMode
import com.clothesmodel.contract.model.VersionSnapshot
import com.clothesmodel.contract.model.WorkflowVersionRef

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param personAssetIds 
 * @param garmentAssetId Server-issued UUIDv7 represented as a canonical UUID string.
 * @param mode 
 * @param generationOptions 
 * @param state 
 * @param providerConfigRef 
 * @param providerSnapshot 
 * @param items 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param updatedAt UTC RFC 3339 timestamp.
 * @param maskAssetId 
 * @param relatedJobId 
 * @param blockReason 
 * @param blockedDetail 
 * @param workflowVersionRef 
 * @param workflowSnapshot 
 */
@Serializable

data class TryOnJob (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "person_asset_ids")
    val personAssetIds: kotlin.collections.List<@Contextual java.util.UUID>,

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "garment_asset_id")
    val garmentAssetId: java.util.UUID,

    @Contextual @SerialName(value = "mode")
    val mode: TryOnMode,

    @SerialName(value = "generation_options")
    val generationOptions: GenerationOptions,

    @Contextual @SerialName(value = "state")
    val state: JobState,

    @SerialName(value = "provider_config_ref")
    val providerConfigRef: ProviderConfigRef,

    @SerialName(value = "provider_snapshot")
    val providerSnapshot: VersionSnapshot,

    @SerialName(value = "items")
    val items: kotlin.collections.List<JobItem>,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "updated_at")
    val updatedAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "mask_asset_id")
    val maskAssetId: java.util.UUID? = null,

    @Contextual @SerialName(value = "related_job_id")
    val relatedJobId: java.util.UUID? = null,

    @Contextual @SerialName(value = "block_reason")
    val blockReason: JobBlockReason? = null,

    @SerialName(value = "blocked_detail")
    val blockedDetail: kotlin.String? = null,

    @SerialName(value = "workflow_version_ref")
    val workflowVersionRef: WorkflowVersionRef? = null,

    @SerialName(value = "workflow_snapshot")
    val workflowSnapshot: VersionSnapshot? = null

) {


}

