/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.AssetKind
import com.clothesmodel.contract.model.ProblemDetails
import com.clothesmodel.contract.model.UploadState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param state 
 * @param assetKind 
 * @param filename 
 * @param contentType 
 * @param sizeBytes 
 * @param uploadedBytes 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param expiresAt UTC RFC 3339 timestamp.
 * @param assetId 
 * @param error 
 */
@Serializable

data class UploadSession (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @Contextual @SerialName(value = "state")
    val state: UploadState,

    @Contextual @SerialName(value = "asset_kind")
    val assetKind: AssetKind,

    @SerialName(value = "filename")
    val filename: kotlin.String,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @SerialName(value = "uploaded_bytes")
    val uploadedBytes: kotlin.Long,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "expires_at")
    val expiresAt: java.time.OffsetDateTime,

    @Contextual @SerialName(value = "asset_id")
    val assetId: java.util.UUID? = null,

    @SerialName(value = "error")
    val error: ProblemDetails? = null

) {


}

