/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.AssetKind
import com.clothesmodel.contract.model.GarmentCategory
import com.clothesmodel.contract.model.GarmentSource

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param assetKind 
 * @param filename 
 * @param contentType 
 * @param sizeBytes 
 * @param garmentCategory 
 * @param garmentSource 
 */
@Serializable

data class UploadCreateRequest (

    @Contextual @SerialName(value = "asset_kind")
    val assetKind: AssetKind,

    @SerialName(value = "filename")
    val filename: kotlin.String,

    @SerialName(value = "content_type")
    val contentType: kotlin.String,

    @SerialName(value = "size_bytes")
    val sizeBytes: kotlin.Long,

    @Contextual @SerialName(value = "garment_category")
    val garmentCategory: GarmentCategory? = null,

    @Contextual @SerialName(value = "garment_source")
    val garmentSource: GarmentSource? = null

) {


}

