/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param label Read-only display label captured when the owning resource was created.
 * @param artifactSha256 Immutable artifact digest captured when the owning resource was created.
 * @param manifestSha256 Immutable manifest digest captured when the owning resource was created.
 * @param bindingsSchemaVersion Version of the Workflow binding contract captured by the job.
 */
@Serializable

data class VersionSnapshot (

    /* Read-only display label captured when the owning resource was created. */
    @SerialName(value = "label")
    val label: kotlin.String,

    /* Immutable artifact digest captured when the owning resource was created. */
    @SerialName(value = "artifact_sha256")
    val artifactSha256: kotlin.String? = null,

    /* Immutable manifest digest captured when the owning resource was created. */
    @SerialName(value = "manifest_sha256")
    val manifestSha256: kotlin.String? = null,

    /* Version of the Workflow binding contract captured by the job. */
    @SerialName(value = "bindings_schema_version")
    val bindingsSchemaVersion: kotlin.Int? = null

) {


}

