/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderCapabilities

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param schemaVersion 
 * @param bindingKeys 
 * @param outputCount 
 * @param capabilities 
 */
@Serializable

data class WorkflowManifestSummary (

    @SerialName(value = "schema_version")
    val schemaVersion: kotlin.Int,

    @SerialName(value = "binding_keys")
    val bindingKeys: kotlin.collections.Set<kotlin.String>,

    @SerialName(value = "output_count")
    val outputCount: kotlin.Int,

    @SerialName(value = "capabilities")
    val capabilities: ProviderCapabilities? = null

) {


}

