/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param workflowId 
 * @param version 
 * @param mode 
 * @param workflowJson Immutable ComfyUI API-format workflow JSON.
 * @param manifest Versioned bindings, outputs, and declared capabilities.
 */
@Serializable

data class WorkflowCreateRequest (

    @SerialName(value = "workflow_id")
    val workflowId: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.Int,

    @SerialName(value = "mode")
    val mode: WorkflowCreateRequest.Mode,

    /* Immutable ComfyUI API-format workflow JSON. */
    @Contextual @SerialName(value = "workflow_json")
    val workflowJson: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>,

    /* Versioned bindings, outputs, and declared capabilities. */
    @Contextual @SerialName(value = "manifest")
    val manifest: kotlin.collections.Map<kotlin.String, kotlinx.serialization.json.JsonElement>

) {

    /**
     * 
     *
     * Values: precise_try_on,unknown_default_open_api
     */
    @Serializable(with = ModeSerializer::class)
    enum class Mode(val value: kotlin.String) {
        @SerialName(value = "precise_try_on") precise_try_on("precise_try_on"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object ModeSerializer : KSerializer<Mode> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Mode {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Mode.entries.firstOrNull { it.value == value }
                ?: Mode.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Mode) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

