/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.WorkflowCheckStatus

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param key Stable machine-readable check key.
 * @param status 
 * @param detail Safe redacted explanation without Workflow bodies, paths, prompts, or secrets.
 */
@Serializable

data class WorkflowValidationCheck (

    /* Stable machine-readable check key. */
    @SerialName(value = "key")
    val key: kotlin.String,

    @Contextual @SerialName(value = "status")
    val status: WorkflowCheckStatus,

    /* Safe redacted explanation without Workflow bodies, paths, prompts, or secrets. */
    @SerialName(value = "detail")
    val detail: kotlin.String? = null

) {


}

