/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.WorkflowCompatibilityState
import com.clothesmodel.contract.model.WorkflowValidationCheck

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param status 
 * @param checkedAt UTC RFC 3339 timestamp.
 * @param checks 
 * @param observedServerVersion Safe server version label observed during the compatibility check.
 */
@Serializable

data class WorkflowCompatibilityResult (

    @Contextual @SerialName(value = "status")
    val status: WorkflowCompatibilityState,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "checked_at")
    val checkedAt: java.time.OffsetDateTime,

    @SerialName(value = "checks")
    val checks: kotlin.collections.List<WorkflowValidationCheck>,

    /* Safe server version label observed during the compatibility check. */
    @SerialName(value = "observed_server_version")
    val observedServerVersion: kotlin.String? = null

) {


}

