/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model

import com.clothesmodel.contract.model.ProviderCapabilities
import com.clothesmodel.contract.model.WorkflowState

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param id Server-issued UUIDv7 represented as a canonical UUID string.
 * @param workflowId 
 * @param version 
 * @param mode 
 * @param state 
 * @param capabilities 
 * @param createdAt UTC RFC 3339 timestamp.
 * @param validationStatus 
 * @param validationMessages 
 * @param activatedAt 
 */
@Serializable

data class WorkflowVersion (

    /* Server-issued UUIDv7 represented as a canonical UUID string. */
    @Contextual @SerialName(value = "id")
    val id: java.util.UUID,

    @SerialName(value = "workflow_id")
    val workflowId: kotlin.String,

    @SerialName(value = "version")
    val version: kotlin.Int,

    @SerialName(value = "mode")
    val mode: WorkflowVersion.Mode,

    @Contextual @SerialName(value = "state")
    val state: WorkflowState,

    @SerialName(value = "capabilities")
    val capabilities: ProviderCapabilities,

    /* UTC RFC 3339 timestamp. */
    @Contextual @SerialName(value = "created_at")
    val createdAt: java.time.OffsetDateTime,

    @SerialName(value = "validation_status")
    val validationStatus: WorkflowVersion.ValidationStatus? = null,

    @SerialName(value = "validation_messages")
    val validationMessages: kotlin.collections.List<kotlin.String>? = null,

    @Contextual @SerialName(value = "activated_at")
    val activatedAt: java.time.OffsetDateTime? = null

) {

    /**
     * 
     *
     * Values: precise_try_on,unknown_default_open_api
     */
    @Serializable(with = ModeSerializer::class)
    enum class Mode(val value: kotlin.String) {
        @SerialName(value = "precise_try_on") precise_try_on("precise_try_on"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object ModeSerializer : KSerializer<Mode> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): Mode {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return Mode.entries.firstOrNull { it.value == value }
                ?: Mode.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: Mode) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }
    /**
     * 
     *
     * Values: not_run,passed,failed,unknown_default_open_api
     */
    @Serializable(with = ValidationStatusSerializer::class)
    enum class ValidationStatus(val value: kotlin.String) {
        @SerialName(value = "not_run") not_run("not_run"),
        @SerialName(value = "passed") passed("passed"),
        @SerialName(value = "failed") failed("failed"),
        @SerialName(value = "unknown_default_open_api") unknown_default_open_api("unknown_default_open_api");
    }

    internal object ValidationStatusSerializer : KSerializer<ValidationStatus> {
        override val descriptor = kotlin.String.serializer().descriptor

        override fun deserialize(decoder: Decoder): ValidationStatus {
            val value = decoder.decodeSerializableValue(kotlin.String.serializer())
            return ValidationStatus.entries.firstOrNull { it.value == value }
                ?: ValidationStatus.unknown_default_open_api
        }

        override fun serialize(encoder: Encoder, value: ValidationStatus) {
            encoder.encodeSerializableValue(kotlin.String.serializer(), value.value)
        }
    }

}

