/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.clothesmodel.contract.model


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual
import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializer
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/**
 * 
 *
 * @param workflowSha256 
 * @param manifestSha256 
 * @param workflowSizeBytes 
 * @param manifestSizeBytes 
 */
@Serializable

data class WorkflowArtifactMetadata (

    @SerialName(value = "workflow_sha256")
    val workflowSha256: kotlin.String,

    @SerialName(value = "manifest_sha256")
    val manifestSha256: kotlin.String,

    @SerialName(value = "workflow_size_bytes")
    val workflowSizeBytes: kotlin.Long? = null,

    @SerialName(value = "manifest_size_bytes")
    val manifestSizeBytes: kotlin.Long? = null

) {


}

